#!/usr/bin/env node
/**
 * Syncs sdk/.env from contracts/.env (RPC_URL, CHAIN_ID) and the latest
 * Foundry broadcast for that chain (contract addresses).
 *
 * Usage:
 *   node scripts/sync-env.mjs
 *   # or from sdk/: pnpm sync-env
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dir = dirname(fileURLToPath(import.meta.url));
const SDK_DIR = resolve(__dir, '..');
const CONTRACTS_DIR = resolve(SDK_DIR, '../contracts');

// ── helpers ──────────────────────────────────────────────────────────────────

function parseEnv(filePath) {
  if (!existsSync(filePath)) return {};
  return Object.fromEntries(
    readFileSync(filePath, 'utf8')
      .split('\n')
      .map(l => l.trim())
      .filter(l => l && !l.startsWith('#') && l.includes('='))
      .map(l => {
        const idx = l.indexOf('=');
        return [l.slice(0, idx).trim(), l.slice(idx + 1).trim()];
      }),
  );
}

// ── read contracts/.env ───────────────────────────────────────────────────────

const contractsEnv = parseEnv(resolve(CONTRACTS_DIR, '.env'));
const rpcUrl = contractsEnv.RPC_URL || '';
const chainId = contractsEnv.CHAIN_ID || '';
const privateKey = contractsEnv.PRIVATE_KEY || '';

if (!chainId) {
  console.error('CHAIN_ID not found in contracts/.env');
  process.exit(1);
}

// ── find latest broadcast ─────────────────────────────────────────────────────

const broadcastDir = resolve(CONTRACTS_DIR, `broadcast/DeployContracts.s.sol/${chainId}`);
const broadcastFile = resolve(broadcastDir, 'run-latest.json');

if (!existsSync(broadcastFile)) {
  console.error(`No broadcast found at: ${broadcastFile}`);
  console.error(`Run: forge script script/DeployContracts.s.sol --broadcast`);
  process.exit(1);
}

const broadcast = JSON.parse(readFileSync(broadcastFile, 'utf8'));

// ── extract addresses by contract name ───────────────────────────────────────

const addresses = {};
for (const tx of broadcast.transactions ?? []) {
  if (tx.transactionType === 'CREATE' && tx.contractName && tx.contractAddress) {
    // keep the last deployment of each name (handles re-deploys)
    addresses[tx.contractName] = tx.contractAddress;
  }
}

const chamber = addresses['Chamber'] || '';
const escrow = addresses['Escrow'] || '';
// script deploys two NamedERC20 tokens in order — tknA first, tknB second
const erc20s = broadcast.transactions
  .filter(tx => tx.transactionType === 'CREATE' && tx.contractName === 'NamedERC20')
  .map(tx => tx.contractAddress);
const tknA = erc20s[0] || '';
const tknB = erc20s[1] || '';

// ── write sdk/.env ────────────────────────────────────────────────────────────

const content = `# Auto-generated by scripts/sync-env.mjs — do not edit by hand
# Source: contracts/.env + broadcast/DeployContracts.s.sol/${chainId}/run-latest.json

RPC_URL=${rpcUrl}
CHAIN_ID=${chainId}
PRIVATE_KEY=${privateKey}

CHAMBER_ADDRESS=${chamber}
ESCROW_ADDRESS=${escrow}
TOKEN_A_ADDRESS=${tknA}
TOKEN_B_ADDRESS=${tknB}
`;

const envPath = resolve(SDK_DIR, '.env');
writeFileSync(envPath, content);

console.log(`Written ${envPath}`);
console.log(`  RPC_URL          = ${rpcUrl}`);
console.log(`  CHAIN_ID         = ${chainId}`);
console.log(`  CHAMBER_ADDRESS  = ${chamber}`);
console.log(`  ESCROW_ADDRESS   = ${escrow}`);
console.log(`  TOKEN_A_ADDRESS  = ${tknA}`);
console.log(`  TOKEN_B_ADDRESS  = ${tknB}`);
